import { createKeyPair, keyPairToObject, createIdentityTicket, verifyIdentityTicket, solveChallenge, ticketToObject, generateRandomChallenge, slimprotoVersion } from './index.js'

console.log('slimproto-core testing script')
console.log('======')
console.log('Test credentials:')
const name = 'TestUser'
const password = 'SomePassword'
const challenge = generateRandomChallenge()
console.log(`| name: ${name}`)
console.log(`| password: ${password}`)
console.log(`| challenge: ${challenge.toString('base64')}`)
console.log(`| version: ${slimprotoVersion}`)
console.log('------')
console.log('Create key pair:')
const keypair = createKeyPair(name, password)
console.log(keypair)
console.log('To object:')
const keypairObject = keyPairToObject(keypair)
console.log(keypairObject)
console.log('------')
console.log('Solve challenge:')
const solve = solveChallenge(challenge, keypairObject.privateKey)
console.log(solve)
console.log('------')
console.log('Create identity ticket:')
const ticket = createIdentityTicket(name, password, challenge)
console.log(ticket)
console.log('To object:')
const ticketObject = ticketToObject(ticket)
console.log(ticketObject)
console.log('------')
console.log('Verify ticket:')
const verify = verifyIdentityTicket(ticket, challenge)
console.log(verify)
